name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'alen babu'
        git config --global user.email 'alenbabualen@gmail.com'
        git remote set-url origin https://github.com/alenbabu/My-Portfolio.git   
        npm run deploy